name: Run Cypress Cucumber Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Run Cypress tests on ${{ matrix.browser }}
        run: npx cypress run --browser ${{ matrix.browser }}